from constants import *

config_data = {
PROJECT_NAME : "vai_all",
DATA_FILENAME : "/home/kanner/vai_projekti_2/data/vai_all_1980-2000_datawl_msd_id-0.json",
GARBAGE_LIST : ["c3sn"],
PRE_ATTR_CONTEXT_WORD :  (("[vV]aivaisten", ""), 
                          ("[Vv]aivainen",  ""),
                          ("[Vv]aivaisen",  ""),
                          ("[Vv]aivais",    "")),
CORRECTION_FILENAME : "Concordance_checkup.xls",
CHECKLIST : (":", "ja", "-ja", ".", "i", "ä", "uus"),
KEYWORD_CLEAN : (
    {"test" : "vaivaisisä", "change": {LEMMA: ("vaivaisisä", "vaivainen"), MSD : (("NUM_Sg", "NUM_Pl")) }},
    {"test" : "vaivainenilta", "change":{LEMMA: ("vaivainenilta", "vaivainen"), MSD:(("NUM_Sg", "NUM_Pl"), ("CASE_Nom", "CASE_Abl"))}},
    {"test" : "~", "change": {LEMMA: ("~", ""), WORD: ("~", "")}}
    ),
COMPOUND_BASE : "vaivainen",
CONTEXT_CORPUS_DIR : "context_word_corpus",
COMP_REPLACEMENTS : {"hoitoapu":"hoito",
        "hoitoasetus":"hoito",
        "hoitoasia":"hoito",
        "hoitohallitus":"hoito",
        "hoitohuone":"hoito",
        "hoitojärjestelmä":"hoito",
        "hoitokunta":"hoito",
        "hoitokysymys":"hoito",
        "hoitolasäädäntö":"hoito",
        "hoitoneuvoja":"hoito",
        "hoitoohjesääntö":"hoito",
        "hoitoolo":"hoito",
        "hoitopoliittinen":"hoito",
        "hoitorasitus":"hoito",
        "hoitotarkastaja":"hoito",
        "hoitotoiminta":"hoito",
        "hoitovirkaomainen":"hoito",
        "huoltoajatus":"huolto",
        "poikalito":"poika",
        "pöllöveistos":"pöllö",
        "ukkokausi":"ukko",
        "ukkonäyttely":"ukko",
        "ukkojaja": "ukko",
        "taloaika": "talo",
        "vaishoidon": "hoito",
        "kotiaika" : "koti",
        "taloajattelu" : "talo"},
CORPUS_FREQUENCIES : [18554915, 130827346, 5928289],
F_THRESHOLD : 50,
SENTENCE_CORPUS_WORDCOUNT : 220155922

}
